add first version of tests

diff --git a/.github/workflows/autotests-hw4-old.yml b/.github/workflows/autotests-hw4-old.yml
--- a/.github/workflows/autotests-hw4-old.yml
+++ b/.github/workflows/autotests-hw4-old.yml
@@ -1,17 +1,20 @@
 name: Autotests-hw4
 
 on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ ]
-
-env:
-  CHART_PATH: todo
-  CONVERTER_IMAGE_NAME: todo
-  ACCOUNTS_IMAGE_NAME: todo
-  IMAGE_TAG: todo
-
+  workflow_call:
+    inputs:
+      chart-path:
+        required: true
+        type: string
+      converter-image-name:
+        required: true
+        type: string
+      accounts-image-name:
+        required: true
+        type: string
+      image-tag:
+        required: true
+        type: string
 
 jobs:
   tests:
@@ -19,29 +22,24 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - uses: actions/checkout@v4
+        with:
+          repository: central-university-dev/hse-autotests
+          ref: main
+          path: tests
+
+
       - name: Start minikube
         uses: medyagh/setup-minikube@master
-        with:
-          cpus: max
-          memory: max
 
       - name: Add helm repo
         run: |
           helm repo add cetic https://cetic.github.io/helm-charts
           helm repo add codecentric https://codecentric.github.io/helm-charts
           helm repo add bitnami https://charts.bitnami.com/bitnami
-          helm repo add vector https://helm.vector.dev
           helm repo update
 
-      - name: Deploy vector
-        continue-on-error: true
-        run: |
-          helm upgrade --install vector vector/vector \
-            --values tests/hw9/vector-values.yml \
-            --set customConfig.sinks.loki.auth.password=${{ secrets.HSE_LOKI_TOKEN }} \
-            --set-string customConfig.sinks.loki.labels.repository='${{ github.repository }}' \
-            --set-string customConfig.sinks.loki.labels.run_id='${{ github.run_id }}' \
-            --wait --timeout 180s   
+
 
       - name: Deploy postgres
         continue-on-error: true
@@ -58,7 +56,7 @@ jobs:
       - name: Deploy rates
         continue-on-error: true
         run: |
-          helm upgrade --install rates $CHART_PATH \
+          helm upgrade --install rates ${{ inputs.chart-path }} \
             --set fullnameOverride=rates \
             --set image.repository=miraclewisp/hse-rates \
             --set image.tag=auth-amd64 \
@@ -68,20 +66,20 @@ jobs:
       - name: Deploy converter
         continue-on-error: true
         run: |
-          helm upgrade --install converter $CHART_PATH \
+          helm upgrade --install converter ${{ inputs.chart-path }} \
             --set fullnameOverride=converter \
-            --set image.repository=$CONVERTER_IMAGE_NAME \
-            --set image.tag=$IMAGE_TAG \
+            --set image.repository=${{ inputs.converter-image-name }} \
+            --set image.tag=${{ inputs.image-tag }} \
             -f tests/hw4/converter-values.yml \
             --wait --timeout 180s
 
       - name: Deploy accounts
         continue-on-error: true
         run: |
-          helm upgrade --install accounts $CHART_PATH \
+          helm upgrade --install accounts ${{ inputs.chart-path }} \
             --set fullnameOverride=accounts \
-            --set image.repository=$ACCOUNTS_IMAGE_NAME \
-            --set image.tag=$IMAGE_TAG \
+            --set image.repository=${{ inputs.accounts-image-name }} \
+            --set image.tag=${{ inputs.image-tag }} \
             -f tests/hw4/accounts-values.yml \
             --wait --timeout 180s
 
@@ -109,18 +107,24 @@ jobs:
       - name: Get test logs
         run: |
           kubectl logs jobs/autotest-job
-          TEST_RESULT=$(kubectl logs jobs/autotest-job | sed -n '/--- TEST RESULTS BEGIN ---/, /--- TEST RESULTS END ---/p' || true)
-          echo "TEST_RESULTS<<EOF" >> $GITHUB_ENV
-          echo "$TEST_RESULT" >> $GITHUB_ENV
+          ERROR_LOGS=$(kubectl logs jobs/autotest-job | grep 'ERROR |' || true)
+          echo "JOB_ERRORS<<EOF" >> $GITHUB_ENV
+          echo "$ERROR_LOGS" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
       - uses: actions/github-script@v7
         with:
           script: |
-            const results = process.env.TEST_RESULTS
+            const errors = process.env.JOB_ERRORS
+            let body = ""
+            if (errors) {
+              body = `### ❌ Ошибки \n\n ${errors}`
+            } else {
+              body = `### ✅ Тесты пройдены`
+            }
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: results
+              body: body
             })
